---
- name: 'Backup IdP credentails only if they have not been backed up'
  copy:
    src: '{{ shib_idp.home }}/credentials/{{ item }}'
    dest: 'assets/{{ inventory_hostname }}/idp/credentials'
    owner: root
    group: root
    mode: 0644
    force: no
  with_items:
  - idp-backchannel.crt
  - idp-backchannel.p12
  - idp-encryption.crt
  - idp-encryption.key
  - idp-signing.crt
  - idp-signing.key
  - idp-backchannel.p12
  - sealer.jks
  - sealer.kver

- name: 'Restore IdP credentials'
  copy:
    src: 'assets/{{ inventory_hostname }}/idp/credentials/{{ item }}'
    dest: '{{ shib_idp.home }}/credentials'
    owner: root
    group: root
    mode: 0644
  with_items:
  - idp-backchannel.crt
  - idp-backchannel.p12
  - idp-encryption.crt
  - idp-encryption.key
  - idp-signing.crt
  - idp-signing.key
  - idp-backchannel.p12
  - sealer.jks
  - sealer.kver

- name: 'Ensure correct credentials for certs'
  file:
    name: '{{ shib_idp.home }}/credentials/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
  - {{ metadata_cert_file_name }}
  - idp-backchannel.crt
  - idp-encryption.key
  - idp-signing.key
  - sealer.jks
  - sealer.kver

- name: 'The eduGAIN cert'
  file:
    name: '{{ shib_idp.home}}/credentials/{{ edugain_metadata_cert_file_name }}'
    owner: root
    group: root
    mode: 0644
  when: {{ enable_edugain }}

- name: 'Ensure correct credentials for keys'
  file:
    name: '{{ shib_idp.home }}/credentials/{{ item }}'
    owner: root
    group: jetty
    mode: 0640
  with_items:
  - idp-backchannel.p12
  - idp-encryption.key
  - idp-signing.key

  copy:
    src: '{{ item }}'
    dest: '{{ shib_idp.home }}/credentials'
    owner: root
    group: root
    mode: 0644
  with_fileglob:
  - 'assets/{{ inventory_hostname }}/idp/credentials/extras/*'
